default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit, pre-push]
repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint
        entry: hatch fmt --linter --check
        types: [python]
        language: system
        pass_filenames: false
      - id: type
        name: Type
        entry: hatch run type:type
        types: [python]
        language: system
        pass_filenames: false